# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
    v.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]

    Disks = [1,2,3,4]
    Disks.each do |hd|
        file_to_disk = "mydisk#{hd}.vmdk"    
        unless File.exist?(file_to_disk)
            v.customize [ "createmedium", "disk", "--filename", file_to_disk, "--format", "vmdk", "--size", 300]
        end
        v.customize [ "storageattach", :id, "--storagectl", "SATA", "--port", "#{hd}", "--device", "0", "--type", "hdd", "--medium", file_to_disk]
    end
  end

  config.vm.provision "shell", path: "script.sh"
end